---
title: "Imputations in Parallel"
author: "Thierry Gosselin"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
# output: 
# pdf_document:
vignette: >
  %\VignetteIndexEntry{"Imputations in Parallel"}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

## Parallel computing in R and stackr

On Mac OSX using OpenMP greatly reduce the computation time for the imputations.
To do the imputations in parallel, you need to install an OpenMP enabled [randomForestSRC](http://www.ccs.miami.edu/~hishwaran/rfsrc.html).
Note that this also works to have 
[data.table](https://github.com/Rdatatable/data.table) work in parallel. 
(time: max 10 minutes).

### Option 1: From source (Linux & Mac OSX) [details here](http://www.ccs.miami.edu/~hishwaran/rfsrc.html)

1. Make sure you have gcc with openmp enabled. 
To check the version of your compiler, in the Terminal:
```r
gcc --version # should be higher than 4.8
```

2. To update your computer's compiler follow this [simple tutorial](http://gbs-cloud-tutorial.readthedocs.io/en/latest/03_computer_setup.html#update-your-computer-s-compiler) (2-5 min)

3. Update your `~/.R/Makevars` file. With MAC OSX use [TextWrangler](http://www.barebones.com/products/textwrangler/) to open the file with `Show hidden items` turned `ON`. You should have these lines:
```r
CC=/usr/local/bin/gcc
CXX=/usr/local/bin/g++
FC=/usr/local/bin/gfortran
F77=/usr/local/bin/gfortran
PKG_LIBS = -fopenmp -lgomp
PKG_CFLAGS= -O3 -Wall -pipe -pedantic -std=gnu99 -fopenmp
PKG_CXXFLAGS=-fopenmp -std=c++11
CFLAGS= -O3 -Wall -pipe -pedantic -std=gnu99 -fopenmp
SHLIB_OPENMP_CFLAGS = -fopenmp
SHLIB_OPENMP_CXXFLAGS = -fopenmp
SHLIB_OPENMP_FCFLAGS = -fopenmp
SHLIB_OPENMP_FFLAGS = -fopenmp
FLIBS=-L/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/finclude # change according to your computer compiler version
CFLAGS=-mtune=native -g -O2 -Wall -pedantic -Wconversion
CXXFLAGS=-mtune=native -g -O2 -Wall -pedantic -Wconversion
```

4. You don't have the file ? Use sudo nano in the Terminal to create one:
```r
cd ~
sudo mkdir ~/.R
sudo nano ~/.R/Makevars
```
Copy/paste the section in step 3. Save and Exit with: `crt-o`, `enter`, `crt-x`.


5. Download and compile randomForestSRC, from the Terminal:
```r
cd ~/Downloads
curl -O https://cran.r-project.org/src/contrib/randomForestSRC_2.4.2.tar.gz
tar -zxvf randomForestSRC_2.4.2.tar.gz
cd randomForestSRC
autoconf
```

6. Install and load randomForestSRC, from R console/RStudio console:
```r
devtools::install_local(path = "~/Downloads/randomForestSRC")
```

### Option 2 (Mac OSX & Windows): Use the pre-compiled binary [instructions here](http://www.ccs.miami.edu/~hishwaran/rfsrc.html)
```r
# NOTES: their is currently a bug with pre-compiled binaries below. Use option 1 until further notice
# Mac OSX
devtools::install_url(url = "http://www.ccs.miami.edu/~hishwaran/rfsrc/randomForestSRC_2.4.2.tgz")
# Windows
devtools::install_url(url = "http://www.ccs.miami.edu/~hishwaran/rfsrc/randomForestSRC_2.4.2.zip")
```
If you opted for option 2 and are still having problems, please use Option 1 ...

## Note

I recommend using [RStudio](https://www.rstudio.com/products/rstudio/download/) 
to run **stackr** or **assigner**. The R GUI is unstable with functions using parallel. 
More details can be found `parallel::mclapply` or on the web. 
Users of third-party front-ends should consult their documentation.
