rm(list=ls())
ls()
library(devtools)
library(reshape2)
library(ggplot2)
library(stringr)
library(stringi)
library(plyr)
library(dplyr) # load this package after plyr to work properly
library(tidyr)
library(readr)
library(ggvis)
library(grid)
library(ggdendro)
library(gridExtra)
library(gplots)
library(adegenet)
library(ape)
library(ade4)
# library(qvalue)
library(HardyWeinberg)
library(diveRsity)
library(hierfstat)
library(microbenchmark)
library(formatR)
library(roxygen2)
formatR::tidy_app()
